import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { ReactQueryProvider } from "@/components/providers/ReactQueryProviser";
// import Link from "next/link";
// import Recenzije from "@/components/Recenzije";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ivan radičev | Život bez boli",
  description: "Generated by create next app",
};

const queryClient = new QueryClient();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReactQueryProvider>
          {/* <div>
          <Link
          href="/rezervacija"
          className="text-md bg-theme1 hover:text-theme1 border-theme1 fixed top-1/2 right-0 z-20 hidden -translate-y-1/2 rounded-4xl border-2 px-5 py-1 font-semibold text-slate-100 uppercase transition-all duration-300 [text-orientation:upright] [writing-mode:vertical-rl] hover:bg-slate-100 sm:inline-block lg:py-2"
          >
          Rezervacija
          </Link>
          </div> */}
          {/* <Recenzije /> */}
          {children}
        </ReactQueryProvider>
      </body>
    </html>
  );
}
